CREATE TABLE  "AUDIT_LOG" 
   (	"LOG_ID" NUMBER, 
	"ACTION" VARCHAR2(20) COLLATE "USING_NLS_COMP", 
	"IP_ADDRESS" VARCHAR2(15) COLLATE "USING_NLS_COMP", 
	"LOG_DATE" DATE, 
	 PRIMARY KEY ("LOG_ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
