CREATE TABLE  "AUTEURS" 
   (	"ID_AUTEUR" NUMBER, 
	"NOM" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"PRENOM" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	 PRIMARY KEY ("ID_AUTEUR")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/