CREATE TABLE  "BOOK_AUDIT" 
   (	"AUDIT_ID" NUMBER, 
	"BOOK_ID" NUMBER, 
	"ACTION" VARCHAR2(10) COLLATE "USING_NLS_COMP", 
	"AUDIT_DATE" DATE, 
	 PRIMARY KEY ("AUDIT_ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
