CREATE TABLE  "EMPRUNTS" 
   (	"ID_EMPRUNT" NUMBER, 
	"ID_UTILISATEUR" NUMBER, 
	"ID_LIVRE" NUMBER, 
	"DATE_DEBUT" DATE, 
	"DATE_FIN" DATE, 
	"STATUT" VARCHAR2(20) COLLATE "USING_NLS_COMP", 
	 CHECK (Statut IN ('En cours', 'Terminé')) ENABLE, 
	 PRIMARY KEY ("ID_EMPRUNT")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
ALTER TABLE  "EMPRUNTS" ADD CONSTRAINT "FK_LIVRES" FOREIGN KEY ("ID_LIVRE")
	  REFERENCES  "LIVRES" ("ID_LIVRE") ENABLE
/
ALTER TABLE  "EMPRUNTS" ADD CONSTRAINT "FK_UTILISATEURS" FOREIGN KEY ("ID_UTILISATEUR")
	  REFERENCES  "UTILISATEURS" ("ID_UTILISATEUR") ENABLE
/
