CREATE TABLE  "LIVRES" 
   (	"ID_LIVRE" NUMBER, 
	"TITRE" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"ID_AUTEUR" NUMBER, 
	"STATUT" VARCHAR2(20) COLLATE "USING_NLS_COMP", 
	"GENRE" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	 CHECK (Statut IN ('Disponible', 'Non disponible')) ENABLE, 
	 PRIMARY KEY ("ID_LIVRE")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
ALTER TABLE  "LIVRES" ADD CONSTRAINT "FK_AUTEURS" FOREIGN KEY ("ID_AUTEUR")
	  REFERENCES  "AUTEURS" ("ID_AUTEUR") ENABLE
/