CREATE TABLE  "UTILISATEURS" 
   (	"ID_UTILISATEUR" NUMBER, 
	"NOM" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"PRENOM" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"EMAIL" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	 PRIMARY KEY ("ID_UTILISATEUR")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
