create or replace TRIGGER UTILISATEURS_UPDATE_DELETE_TRIGGER
AFTER UPDATE OR DELETE ON utilisateurs
FOR EACH ROW
DECLARE
  v_ip VARCHAR2(100);
BEGIN
  v_ip := SYS_CONTEXT('USERENV', 'IP_ADDRESS');
  
  INSERT INTO AUDIT_LOG (log_id, ACTION, IP_ADDRESS, LOG_DATE)
  VALUES (SEQUENCE_AUDIT_LOG.NEXTVAL,
          CASE
            WHEN UPDATING THEN 'UPDATE'
            WHEN DELETING THEN 'DELETE'
          END,
          v_ip,
          SYSTIMESTAMP);
END;
